// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe61w1oQ4VnBNsagTgSCpDuAgtGTbfEFE',
    appId: '1:208670504158:web:830ada56f63345ce26be4f',
    messagingSenderId: '208670504158',
    projectId: 'fluttertry-13037',
    authDomain: 'fluttertry-13037.firebaseapp.com',
    storageBucket: 'fluttertry-13037.appspot.com',
    measurementId: 'G-WTYGSD7E6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtT9BWP1TgowoeG8kh7CIX3NM4throvhU',
    appId: '1:208670504158:android:22960e48043da65026be4f',
    messagingSenderId: '208670504158',
    projectId: 'fluttertry-13037',
    storageBucket: 'fluttertry-13037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_x8M9DdvVTOFmSFcfTJPMlDn38LuILso',
    appId: '1:208670504158:ios:b97dcf6846ee0ce626be4f',
    messagingSenderId: '208670504158',
    projectId: 'fluttertry-13037',
    storageBucket: 'fluttertry-13037.appspot.com',
    iosClientId: '208670504158-jvuepmknjleur67astlk0sdok47fikjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_x8M9DdvVTOFmSFcfTJPMlDn38LuILso',
    appId: '1:208670504158:ios:ec2c4b8b7dab9e0426be4f',
    messagingSenderId: '208670504158',
    projectId: 'fluttertry-13037',
    storageBucket: 'fluttertry-13037.appspot.com',
    iosClientId: '208670504158-ihpabut2aae6vk5pmq310ltv3re1ab2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTry.RunnerTests',
  );
}
